### ISSUE TITLE
Wheels

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#16]
Despre ce roti o sa folosim. Cand aveti o idee scrieti codul rotilor si de ce sa le folosim pe alea.

**Comment by LucaVictor** [comment]
Folosirea unei suspensii deasupra intake-ului pentru downforce sporit

**Comment by matei8** [comment]
Aprob ideea asta dar zic sa o punem in aplicare dupa ce facem teste si vedem daca e nevoie

**Comment by matei8** [comment]
Avand in vedere ca acest issue a trecut de deadline
Pana maine vreau sa stabilim ce roti folosim la intake

**Comment by matei8** [comment]
Eu zic sa folosim rotile de 30 mm  pt ca in afara de alea avem numai de 90 mm care sunt prea mari (30 mm -> REV-41-1353)

**Comment by matei8** [comment]
Si plus ca avem in total 16 rotite
Si am sa fac acum niste calcule sa vedem cate ne-ar trebui in total

**Comment by matei8** [comment]
Ok deci am facut calculele si o sa punem 8 rotite pe un ax custom probabil de 210 mm 
And that's that,  daca nu e bine, dupa ce facem teste o sa redechidem issue.

**Comment by LucaVictor** [comment]
Avem o problema la rotile de 30mm. Modelul de CAD o sa va lamureasca
![image](https://user-images.githubusercontent.com/76179120/105016300-26817f00-5a4b-11eb-97f4-6d58deb580f6.png)
![image](https://user-images.githubusercontent.com/76179120/105016352-36995e80-5a4b-11eb-8903-52e0dc634db4.png)
dupa cum se poate observa rotile mici nu au diametrul suficient de mare, iar tot sistemul de intake este expus. 
Avem 2 variante: ori folosim rotile alea de 60(le printam, le imprumutam nush cum facem) ori regandim tot sistemul de intake.

**Comment by matei8** [comment]
at e o problema destul de mare

**Comment by matei8** [comment]
din perspectiva mea putem face 2 chestii:
-Sa punem roti mai mari (60 mm) dar nu de 90 mm pt ca sunt prea mari
-Sau sa modificam structura

**Comment by matei8** [comment]
NOTE: NU AVEM ROTI DE 60mm !!!

**Comment by LucaVictor** [comment]
Chiar nu avem nicio roata de 60 ?
Nici macar una

**Comment by matei8** [comment]
Nu... dar gasim altceva, cred cum stiu cum sa facem, o sa ma uit pe piese si am scriu

**Comment by matei8** [comment]
Deci o varianta ar fi sa printam niste roti de 60 mm daca avem voie si dupa sa le dam cu ceva sticky pe suprafata 
#17

**Comment by matei8** [comment]
> Deci o varianta ar fi sa printam niste roti de 60 mm daca avem voie si dupa sa le dam cu ceva sticky pe suprafata
> #17

@TakingTheRisk

**Comment by TakingTheRisk** [comment]
Da frate se face

**Comment by matei8** [comment]
Beautiful

**Comment by Andrei-Iatagan** [comment]
În cazul în care nu găsim o modalitate de a folosi roți deja făcute, propun două variante alternative : 

i) (am văzut la o altă echipă ceva asemănător, link : https://www.youtube.com/watch?v=j5b6PV39Toc) Să folosim un ax cu niște tentacule flexibile, făcute din tub de perfuzie /elastic de praștie/ furtun.

ii) (nu am văzut în altă parte, deci nu sunt sigur cât de bine ar merge, dar cred că e ok) Să folosim un tambur în loc de roți, făcut dintr - o țeavă de PVC, cu două capace(să intre stea mai bine :)), acoperit cu o suprafață antiaderentă (cauciuc, heatshrink tubing, ceva spray ...)

**Comment by Andrei-Iatagan** [comment]
#IDEI ?#
dacă are cineva vreo idee pentru a putea fixa și centra un tambur din țeavă PP pe un ax hexagonal ... este binevenit. (cred că puteți să „testați” acasă cu un tub de rolă de șervețele ...). 
tl, dr : dacă ști cum să pui tamburul mai bine pe ax, scrie aici

**Comment by matei8** [comment]
> #IDEI ?#
> 
> dacă are cineva vreo idee pentru a putea fixa și centra un tambur din țeavă PP pe un ax hexagonal ... este binevenit. (cred că puteți să „testați” acasă cu un tub de rolă de șervețele ...). 
> 
> tl, dr : dacă ști cum să pui tamburul mai bine pe ax, scrie aici

Adica cum sa bagi axul sau cum sa il faci sa stea neclintit?
