### ISSUE TITLE
Motion system

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#17]
Cum o sa fie pus in miscare si ce componente vor fi folosite si de ce (se va da coudl produsului si motivul alegerii lui).

**Comment by matei8** [comment]
![image](https://user-images.githubusercontent.com/73193029/104368929-6addbe00-5525-11eb-8524-2fc862d9f763.png)

**Comment by matei8** [comment]
Asta ar fi in mare Intake systemul

**Comment by matei8** [comment]
As vrea sa aduc tot bratul ala mai in fata pt ca dupa nu cred ca o sa mai incapa #18 (Conveyerul)

**Comment by LucaVictor** [comment]
Incape la fix, si nu stiu ce modificari laterale mai putem aduce

**Comment by costaalacuparmare** [comment]
Susțin acest design de intake si folosirea unor arcuri pentru suspensie

**Comment by LucaVictor** [comment]
Folosirea unei suspensii deasupra intake-ului pentru downforce sporit ar fi o solutie, astfel incat sa folosim si rotile mai mici de 30mm

**Comment by matei8** [comment]
> Folosirea unei suspensii deasupra intake-ului pentru downforce sporit ar fi o solutie, astfel incat sa folosim si rotile mai mici de 30mm

Cred ca mai intai trebuie sa facem teste sa vedem cum reactioneaza fara arcuri pt ca nu sunt chiar usor de  facut arcurile alea si ne ia din timp

**Comment by matei8** [comment]
Bratul o sa il facem din extrusionuri de 225 mm (REV-41-1431) pt ca au cea ma decenta lungime pt ce ne trebuie noua

**Comment by matei8** [comment]
Inca ma gandesc ce hex sa folosim si daca e nevoie sa taiem dintr-unul

**Comment by LucaVictor** [comment]
Ar cam trebui sa taiem

**Comment by LucaVictor** [comment]
Am creat urmatorul sistem de intake, insa are si el probleme lui, o sa postez aici un prototip sa va faceti o idee. 
![image](https://user-images.githubusercontent.com/76179120/105076893-5bfe8a80-5a94-11eb-846f-67e66c5de3cd.png)
Acesta este sistemul de tractiune, in schimb incercand sa rezolv problema anterioara, am dat in alta.
![image](https://user-images.githubusercontent.com/76179120/105076999-85b7b180-5a94-11eb-9df5-1cf886477f0b.png)
Se poate observa cum pur si simplu rotile nu reusesc sa atinga elementul de joc. O solutie ar fi sa ne printam rotile sau sa le folosim pe cele de 60

**Comment by LucaVictor** [comment]
Voi ce credeti ?

**Comment by LucaVictor** [comment]
Sistemul vechi merge, 
![image](https://user-images.githubusercontent.com/76179120/105077777-a9c7c280-5a95-11eb-80db-231a1f9f8ed7.png)
In schimb uitati cat de aproape este roata dintata de pamant/ elementul de joc
![image](https://user-images.githubusercontent.com/76179120/105077855-c8c65480-5a95-11eb-97a3-f892b65b5d0b.png)
Voi ce parere aveti ?

**Comment by matei8** [comment]
> Am creat urmatorul sistem de intake, insa are si el probleme lui, o sa postez aici un prototip sa va faceti o idee. 
> 
> ![image](https://user-images.githubusercontent.com/76179120/105076893-5bfe8a80-5a94-11eb-846f-67e66c5de3cd.png)
> 
> Acesta este sistemul de tractiune, in schimb incercand sa rezolv problema anterioara, am dat in alta.
> 
> ![image](https://user-images.githubusercontent.com/76179120/105076999-85b7b180-5a94-11eb-9df5-1cf886477f0b.png)
> 
> Se poate observa cum pur si simplu rotile nu reusesc sa atinga elementul de joc. O solutie ar fi sa ne printam rotile sau sa le folosim pe cele de 60

Esteopusul ideii de brat, pentru ca bratul ala e ca sa nu se miste tot robotul la interactiunea cu cercul, ci numai bratul

**Comment by matei8** [comment]
Ramanem tot pe varianta cu bratul

**Comment by matei8** [comment]
Trebuie sa schimbam putin structura bratului si o sa va zic imediat cum

**Comment by matei8** [comment]
Deci rev-41-1303
![Untitled](https://user-images.githubusercontent.com/73193029/105080463-869f1200-5a99-11eb-84e3-80681cfc8175.png)
Este din plastic si nu cred ca e o idee buna sa mentina axul care va primi atatea socuri, si oricum eu propun sa schimbam piesa asta cu unu cu margini mai mici

**Comment by LucaVictor** [comment]
Nu cred ca asta ar fi o problema, in schimb daca am printa structura rotilor de 60 si le-am infasura intr-o banda elastica. Am ajunge la acelasi rezultat. Sau putem cumpara filament siliconat si sa printam rotile la dif densitati

**Comment by matei8** [comment]
> Nu cred ca asta ar fi o problema, in schimb daca am printa structura rotilor de 60 si le-am infasura intr-o banda elastica. Am ajunge la acelasi rezultat. Sau putem cumpara filament siliconat si sa printam rotile la dif densitati

sa stii ca am putea face asta
@TakingTheRisk  crei ca poti face asta ?

**Comment by LucaVictor** [comment]
Stelute + teava pvc pt intake 
![image](https://user-images.githubusercontent.com/76179120/105223065-fa0d5600-5b63-11eb-91cd-796888e927eb.png)
https://www.youtube.com/watch?v=-ujskulDkoo

**Comment by matei8** [comment]
Eu propun sa folosim un tub de pvc cu gauri hexagonale in capete

**Comment by matei8** [comment]
Si putem sa il facem stick cu banda adeziva dubla, si putem sa o uzam putin inainte ca sa nu fie asa lipicioasa

**Comment by LucaVictor** [comment]
Intake tip tambur 
![image](https://user-images.githubusercontent.com/76179120/105348538-26bb7f00-5bf1-11eb-853b-31e3fa08140d.png)
![image](https://user-images.githubusercontent.com/76179120/105348595-3d61d600-5bf1-11eb-9a02-2ced255fdd5d.png)
![image](https://user-images.githubusercontent.com/76179120/105348622-48b50180-5bf1-11eb-96c4-f94bbc7bb982.png)
Distanta fata de sol este aprox 72mm (71.897 mai exact sau 7,2 cm), am senzatia ca o sa ne trebuiasca mai mult downforce. Voi ce credeti ? @NegruAdam @TakingTheRisk @matei8 @Andrei-Iatagan @MateiBusoiu @pe_oricine_altcineva_am_uitat_sa_includ

**Comment by LucaVictor** [comment]
Intake ramificatii:
[] tambur
[]stelute

**Comment by LucaVictor** [comment]
Intake ramificatii 
-[ ] tambur
-[ ] stelute

**Comment by LucaVictor** [comment]
Intake obiective:
- [ ] tambur
- [ ] stelute
- [ ] excursie la dedeman

**Comment by matei8** [comment]
> Intake tip tambur
> ![image](https://user-images.githubusercontent.com/76179120/105348538-26bb7f00-5bf1-11eb-853b-31e3fa08140d.png)
> ![image](https://user-images.githubusercontent.com/76179120/105348595-3d61d600-5bf1-11eb-9a02-2ced255fdd5d.png)
> ![image](https://user-images.githubusercontent.com/76179120/105348622-48b50180-5bf1-11eb-96c4-f94bbc7bb982.png)
> Distanta fata de sol este aprox 72mm (71.897 mai exact sau 7,2 cm), am senzatia ca o sa ne trebuiasca mai mult downforce. Voi ce credeti ? @NegruAdam @TakingTheRisk @matei8 @Andrei-Iatagan @MateiBusoiu @pe_oricine_altcineva_am_uitat_sa_includ

E ok, se putea sa aibe un diamentru mai mare dar merge si asa dac tot am cumparat deja

**Comment by matei8** [comment]
Avem un 20 tooth sprocket (REV-41-1340) care este in plus pe partea dreapta a drivetrainului (efectiv nu are un rol in miscare) si pentru ca am folosit deja toate 20 tth sprocketurile o sa il scoatem p-ala de-acolo si inn locul lui o sa punem un spacer de 15 mm (REV-41-1323).

**Comment by matei8** [comment]
In rest nu am depasit limita de piese asa ca e ok si deocamdata am terminat cu intake systemul si ne apucam de Conveyer #18

**Comment by matei8** [comment]
Daca mai are cineva ceva de adaugat, in seara asta as vrea sa scrie aici.
