### ISSUE TITLE
Conveyer

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#18]
Despre portiunea dintre intake si Shooting System. (depinde de #17 )

**Comment by LucaVictor** [comment]
Folosirea unor roti care sa impinga inelele in shooter + un stabilizator 
![image](https://user-images.githubusercontent.com/76179120/104363907-8396a580-551e-11eb-8bff-c16a723bb805.png)
Avand in vedere ca asta este drivetrain-ul nostru
![image](https://user-images.githubusercontent.com/76179120/104364042-b6d93480-551e-11eb-89fa-4b2f4e5ab2d4.png)
Plus un stabilizator care sa centreze inelul pt shooter

**Comment by matei8** [comment]
Astea sunt pt intake
Muta-le pe intake

**Comment by MihaiBobeica** [comment]
Propun  folosirea rotilor de 30mm pentru conveyer, pentru stabilizator folosim elementul de intake.

**Comment by matei8** [comment]
Prin stabilizator la ce va referiti ?

**Comment by MihaiBobeica** [comment]
inelele când intră în teren sunt așezate vertical. Mă gândesc că un stabilizator are rolul de a le așeza pe teren, fiind un element incorporat in intake.

**Comment by matei8** [comment]
Aici o sa discutam rezultatele finale de la #26 si #25

**Comment by matei8** [comment]
Deci o sa folosim o rampa de policarbonat sau orice material (nu trebuie sa fie f rigid) ca sa indreptam inelele spre conveyer si ulterior shooting

**Comment by matei8** [comment]
Avand in vedere ca nu e benefic sa folosim tuburile chirurgicale pt conveyer o sa folosim roti pe lateral care duc spre shooter

Intre ele va fi o panta de policarbonat
Tot sistemul va fi sustinut pe 2 C cahnneluri de 248 mm la un unghi de 45
Pareri ?

**Comment by LucaVictor** [comment]
Piesa facuta in 3D care ne scuteste ne o gramada de piese si care in principiu coboara al doilea shaft pt a putea aduna piesele.
![image](https://user-images.githubusercontent.com/76179120/107117055-2c1af980-6880-11eb-80fb-d50f8ca80c3f.png)
![image](https://user-images.githubusercontent.com/76179120/107117029-08f04a00-6880-11eb-9eaa-2b7ffa992967.png)
![image](https://user-images.githubusercontent.com/76179120/107117034-0beb3a80-6880-11eb-90d8-34442f52bda6.png)
![image](https://user-images.githubusercontent.com/76179120/107117041-11e11b80-6880-11eb-943a-4c8a9fe1b2a2.png)

Credite @TakingTheRisk pt ca m-a ajutat sa o fac. Va rog frumos sa spuneti ceva ca sa vedem daca o printam sau mai facem modificari

**Comment by matei8** [comment]
Eu cred ca e f buna piesa atata timp cat nu se mai freaca de ea shaft collar-ul

**Comment by matei8** [comment]
dar cum vine lantul pe hex shaft ?

**Comment by LucaVictor** [comment]
> dar cum vine lantul pe hex shaft ?

pun eu acm un sprocket

**Comment by matei8** [comment]
> > dar cum vine lantul pe hex shaft ?
> 
> pun eu acm un sprocket

Unde ? ca nu prea are loc (btw trebuie sa fie aliniat si cu sprocketu de sus

**Comment by LucaVictor** [comment]
> > > dar cum vine lantul pe hex shaft ?
> > 
> > 
> > pun eu acm un sprocket
> 
> Unde ? ca nu prea are loc (btw trebuie sa fie aliniat si cu sprocketu de sus

pot sa modific spatiul dintre rotile de 30

**Comment by TakingTheRisk** [comment]
Eu tot n-am inteles dc a picat faza cu cablurile surgicale?

**Comment by matei8** [comment]
Pt ca practic n-avem cum sa le prindem
Trebuia sa facem ca un fel de camaruta pt fiecare tub (ca sa aibe aderenta si sa nu se invarta in gol shaftu) pe fiecare ax si alea le faceam din Short Bearing-uri de care am putea sa mai printam dar o sa vb cu totii luni seara ka sedinta si luam o decizie impreuna

**Comment by TakingTheRisk** [comment]
Negativ, nu am putea printa Short bearing-uri, nu pot printa cercuri.

Si nu ar trb neapara o camaruta tho? doar un canal si sa fie destul de intinse cablurile incat sa aiba frecare destula

**Comment by matei8** [comment]
> Negativ, nu am putea printa Short bearing-uri, nu pot printa cercuri.
> 
> 
> 
> Si nu ar trb neapara o camaruta tho? doar un canal si sa fie destul de intinse cablurile incat sa aiba frecare destula
> 
> 

Problema e ca aluneca si n-au grip si daca nu poti printa cercuri, at facem cealalta varianta

**Comment by matei8** [comment]
Am o idee pt cum sa construim conveyerul:

Dupa cum ati vazut, pe drivetrain sunt puse vertical doua extrusionuri (in dreapta si in stanga) si pe ele putem sa punem 15MM PLASTIC 120 DEGREE BRACKET ( REV-41-1311) si pt fiecare parte sa facem ca un brat de la intake 
![Intake arm](https://user-images.githubusercontent.com/73193029/107751074-9373f600-6d25-11eb-8e8a-9fa2b7e447ac.png)
