### ISSUE TITLE
Cum tragem ???

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#19]
Cum tragem  ?? :))

**Comment by matei8** [comment]
https://www.joom.com/en/products/5cc6ee071436d4010143a679
Daca am pune motorul pe drivetrain(sub shooter anyway) si dupa am pune axul de la flywheel in asta am salva spatiu (sa nu iesim din parametrii)

**Comment by TakingTheRisk** [comment]
![image](https://user-images.githubusercontent.com/61249243/109199445-2130f600-77a8-11eb-9587-6a9ede89c1ec.png)

O idee. Ce-ar fii sa folosim 2 roti(inegale ca altfel nu incape) ca sa reducem putin din bolta pe stanga? 
In chestia de mai sus e calculat sa fie si destula presiune pe inel ca sa fie destula frecare.

**Comment by matei8** [comment]
Si adica sa fie conectat motorul si la ala ?

**Comment by TakingTheRisk** [comment]
Ye, cu un lant pe deasupra.
Aprox. 490mm give or take 20mm

**Comment by LucaVictor** [comment]
nu cred ca suruburile alea lungi o sa tina toata structura si motorul

**Comment by matei8** [comment]
> Ye, cu un lant pe deasupra.
> Aprox. 490mm give or take 20mm

si care era limita ?

**Comment by matei8** [comment]
> ![image](https://user-images.githubusercontent.com/61249243/109199445-2130f600-77a8-11eb-9587-6a9ede89c1ec.png)
> 
> O idee. Ce-ar fii sa folosim 2 roti(inegale ca altfel nu incape) ca sa reducem putin din bolta pe stanga?
> In chestia de mai sus e calculat sa fie si destula presiune pe inel ca sa fie destula frecare.

stai ca acum am vazut defapt ce ai facut acum, and it's good, dar sa gasim cum sa facem sa aducem aia de plastic mai aproape de extrusion

**Comment by matei8** [comment]
Am o idee care cred ca e destul de buna dar trebuie sa ma ajute cineva s-o bag in fusion

**Comment by LucaVictor** [comment]
Acesta este abordarea mea
![image](https://user-images.githubusercontent.com/76179120/109391736-4dbc4d80-7921-11eb-851f-7337228de6e4.png)

Sistemul se bazeaza pe 2 C channel-uri puse vertical legate cu 2 tipuri de 90 degree bracket
![image](https://user-images.githubusercontent.com/76179120/109391743-54e35b80-7921-11eb-89c5-c26bbf955547.png)

Sistemul shooter basic (atat pe robot cat si individual )
![image](https://user-images.githubusercontent.com/76179120/109391758-69bfef00-7921-11eb-8283-9d3e6c903f3d.png)
![image](https://user-images.githubusercontent.com/76179120/109391772-76dcde00-7921-11eb-98d2-db82944b91fe.png)

Am incercat sa gasesc si gauri pt suruburi, are 3 puncte dar nu formeaza un triunghi, asta mai ajustam manual
![image](https://user-images.githubusercontent.com/76179120/109391870-eeab0880-7921-11eb-8d70-5fee9ebe35c4.png)

Cu putin ajutor se aliniaza perfect cu roata de 90

![image](https://user-images.githubusercontent.com/76179120/109391892-113d2180-7922-11eb-929a-ed3445f15d39.png)

Mai multe poze: 

![image](https://user-images.githubusercontent.com/76179120/109391918-2c0f9600-7922-11eb-8668-8f252e5cf6da.png)
![image](https://user-images.githubusercontent.com/76179120/109391925-316ce080-7922-11eb-99d1-ea8512dfe077.png)
![image](https://user-images.githubusercontent.com/76179120/109391957-40539300-7922-11eb-8b3f-e934d3b73858.png)

**Un dezavantaj** ar fi ca nu mai ramanem cu channel-uri dupa implementarea acestui sistem.

**Comment by LucaVictor** [comment]
Astept opinii !!!!!!

**Comment by matei8** [comment]
pare ok, dar lantul o sa vina deasupra pe la policarbonat nu ?
btw pune roti de 60 mm

**Comment by LucaVictor** [comment]
La varianta pe care am zis-o eu cu shaftul de conveyer pe channel, am incercat ceva in fusion  si cam asta a iesit. Tin sa mentionez  ca diametrul tubului chirurgical calculat de mine in fusion ochiometric are 5.50mm diametru, iar distanta dintre pulley si channel este de 5.80mm 

![image](https://user-images.githubusercontent.com/76179120/109667299-ac2f3900-7b78-11eb-8173-a6c2e302e0a4.png)

Se aliniaza ok, cu extrusion-urile
![image](https://user-images.githubusercontent.com/76179120/109667482-da147d80-7b78-11eb-9087-61d43a24c7f3.png)

Dar provocarea adevarata va fi sa alinem endcapul cu channel ul acolo
![image](https://user-images.githubusercontent.com/76179120/109667525-e6003f80-7b78-11eb-9d15-fc638f977330.png)

Astept  opinii !!!!!!!

**Comment by LucaVictor** [comment]
As vrea sa stiu ce credeti ca sa stiu ce fac mai incolo, un flat plate ar fi perfect, poate intrebam pe xeo pe server poate ne ajuta cineva :))))))))))))

**Comment by matei8** [comment]
Pune si tuburile ca am impresia ca intra in C Channel

**Comment by Andrei-Iatagan** [comment]
pare ok, dar tot va fi nevoie sa punem ceva care sa faca inelul sa stea la acelasi nivel mereu.

**Comment by matei8** [comment]
> pare ok, dar tot va fi nevoie sa punem ceva care sa faca inelul sa stea la acelasi nivel mereu.
> 
> 

Trebuie sa facem si o inclinatie cand ajunge la shooter pt ca nu trage destul de sus, ma gandesc sa facem o rampa de 3-4 cm (sau mai putin) dupa shooter

**Comment by LucaVictor** [comment]
> Pune si tuburile ca am impresia ca intra in C Channel

tuburile in 3D sunt facute cam de forma, masuratorile nu sunt exacte, vb cu teo sa aflu exact masuratorile
In schimb dupa cum am zis, un flat plate ar fi perfect, asa ca as intreba pe xeo.
Din research-ul meu reiese ca nu ar trb sa ne fie frica sa folosim si piese custom din lemn sau plastic

**Comment by LucaVictor** [comment]
> > pare ok, dar tot va fi nevoie sa punem ceva care sa faca inelul sa stea la acelasi nivel mereu.
> 
> Trebuie sa facem si o inclinatie cand ajunge la shooter pt ca nu trage destul de sus, ma gandesc sa facem o rampa de 3-4 cm (sau mai putin) dupa shooter

Asta nu e problema

**Comment by LucaVictor** [comment]
Teo mi-a zis ca are aprox 3mm diametru, ceea ce este super si se portriveste

**Comment by LucaVictor** [comment]
Dezavantejele in schimb ale acestui sistem sunt ca o sa avem nevoie de un shaft mai lung, se obs si in poza
![image](https://user-images.githubusercontent.com/76179120/109791440-21ebe100-7c1b-11eb-811b-8498e4e8e374.png)

Dar si tuburi chirurgicale mai lungi

**Comment by LucaVictor** [comment]
Am pus ala si nu merge, teoretic am putea trage de tub, dar arata cam asa
![image](https://user-images.githubusercontent.com/76179120/109805463-22d93e80-7c2c-11eb-8cf9-6bb093024ef0.png)
![image](https://user-images.githubusercontent.com/76179120/109805482-28cf1f80-7c2c-11eb-8301-71235992d722.png)

Noi acum putem sa impingem de tub in jos pana se loveste de channel, dar nush  cat de eficient este :/

**Comment by LucaVictor** [comment]
Am incercat sa ridic tot ansamblul o gaura mai sus, si chiar daca distanta dintre inel si tub s-a miscsorat,  inelul are acm mare damb de intampinat

![image](https://user-images.githubusercontent.com/76179120/109805861-a1ce7700-7c2c-11eb-91d1-3dc6ef1ef88f.png)
![image](https://user-images.githubusercontent.com/76179120/109805890-ab57df00-7c2c-11eb-88fd-a847c01e15b1.png)

**Comment by matei8** [comment]
Eu zic sa lasam asta pt ca ne complicam si se modifica multe si plus ca merge si fara conveyerul extins diferenta e ca daca facem conveyerul pana in shooter nu ne mai trebuie rampa aia de policarbonat sau din ce o facem.

**Comment by LucaVictor** [comment]
atunci vad doar o singura solutie, si aceea sa creeam ca niste canale, de preferat lemn care sa ghideze inelul spre roata
![image](https://user-images.githubusercontent.com/76179120/109841923-37c8c880-7c52-11eb-8981-c1df424b268f.png)

ceva in genul asta

![image](https://user-images.githubusercontent.com/76179120/109842026-53cc6a00-7c52-11eb-9a49-124ab8b43722.png)

putem sa facem cad-ul  astfel incat lemnul sa intre pe aici si sa aiba o pozitie oblica(efectiv ii dam slide pe extrusion)

![image](https://user-images.githubusercontent.com/76179120/109842285-95f5ab80-7c52-11eb-92bf-711166ea8a42.png)
 
iar mai sus la channel punem cum zice matei policarbonatul  ala ca sa nivelam.

![image](https://user-images.githubusercontent.com/76179120/109842525-d35a3900-7c52-11eb-8382-f0979ecf3b41.png)

**Comment by matei8** [comment]
Yes, cred ca e cea mai eficienta chetstie pe care o putem face.

**Comment by TeodorRuse** [comment]
Ca sa ridicam inelul, in loc de chestia cu carton si scotch care e acum, nu putem sa punem bucata aia de teava pe bara de jos, asa cum era inainte?

**Comment by LucaVictor** [comment]
o incerc in fusion si iti zic, dar cred ca  da

**Comment by LucaVictor** [comment]
> Yes, cred ca e cea mai eficienta chetstie pe care o putem face.

@TakingTheRisk te ocupi tu de niste schite ?

**Comment by LucaVictor** [comment]
De asemenea, daca stie cineva niste locuri unde au CNC sau orice alta masina pt efectuarea unuei asemenea piese, este binevenit sa scrie aici

Eu am gasit atelierul asta dupa un search, dar cred ca avem optiuni mai bune: https://cnc-3d.ro/index.html

**Comment by matei8** [comment]
> De asemenea, daca stie cineva niste locuri unde au CNC sau orice alta masina pt efectuarea unuei asemenea piese, este binevenit sa scrie aici
> 
> 
> 
> Eu am gasit atelierul asta dupa un search, dar cred ca avem optiuni mai bune: https://cnc-3d.ro/index.html

Stiu eu cui

**Comment by LucaVictor** [comment]
> > De asemenea, daca stie cineva niste locuri unde au CNC sau orice alta masina pt efectuarea unuei asemenea piese, este binevenit sa scrie aici
> > Eu am gasit atelierul asta dupa un search, dar cred ca avem optiuni mai bune: https://cnc-3d.ro/index.html
> 
> Stiu eu cui, sa-mi dati schita cu piesa dupa ce e gata

Cat ne-ar costa si cat ar dura ?

**Comment by matei8** [comment]
Nu stiu sigur sa va spun
Imi trebuie schita si dupa va spun, si cel mai probabil pt noi e moka :))

**Comment by LucaVictor** [comment]
Am facut niste schite, o sa mai lucrez la curba aia, o sa mai modific niste detalii, dar asa arata in mare
![image](https://user-images.githubusercontent.com/76179120/109963610-4caa6800-7cf5-11eb-9855-b217218c875a.png)
![image](https://user-images.githubusercontent.com/76179120/109963792-7b284300-7cf5-11eb-9699-1b9f6fe09fc9.png)

Design usor de pus, dar trb sa scoatem shooterul deci nu e asa usor de pus :)))))))))
![image](https://user-images.githubusercontent.com/76179120/109963903-a01cb600-7cf5-11eb-9aa3-0b6136197fde.png)

Cam asa  arata inelul in pozitia de tragere, e perfect pt ca il si strange putin, cel putin in teorie
![image](https://user-images.githubusercontent.com/76179120/109964055-d65a3580-7cf5-11eb-8379-fd3adf2bdb46.png)

Am largit putin bucata din dreapta ca sa-l si ghideze

![image](https://user-images.githubusercontent.com/76179120/109964170-fab61200-7cf5-11eb-81e0-af69d118d30c.png)

**Comment by LucaVictor** [comment]
Astept opinii

**Comment by matei8** [comment]
Da e ok dar aia din dreapta nu trebuie neaparat dar stai asa ca acum mi-am dat seama... de ce nu printam piesa ca e mult mai rapid

**Comment by matei8** [comment]
Defapt ba da e buna si aia din dreapta dar conteaza numai partea aia de langa flywheel

**Comment by LucaVictor** [comment]
> Da e ok dar aia din dreapta nu trebuie neaparat dar stai asa ca acum mi-am dat seama... de ce nu printam piesa ca e mult mai rapid 

Pt ca are 22,5 cm, și efectiv consumam prea mult plastic degeaba

**Comment by LucaVictor** [comment]
Nu cred că Alex are atâta spatiu

**Comment by matei8** [comment]
> Am facut niste schite, o sa mai lucrez la curba aia, o sa mai modific niste detalii, dar asa arata in mare
> 
> ![image](https://user-images.githubusercontent.com/76179120/109963610-4caa6800-7cf5-11eb-9855-b217218c875a.png)
> 
> ![image](https://user-images.githubusercontent.com/76179120/109963792-7b284300-7cf5-11eb-9699-1b9f6fe09fc9.png)
> 
> 
> 
> Design usor de pus, dar trb sa scoatem shooterul deci nu e asa usor de pus :)))))))))

De ce trebuie scos shooterul ? Ca ala il montam pe conveyer nu ?
> 
> ![image](https://user-images.githubusercontent.com/76179120/109963903-a01cb600-7cf5-11eb-9aa3-0b6136197fde.png)
> 
> 
> 
> Cam asa  arata inelul in pozitia de tragere, e perfect pt ca il si strange putin, cel putin in teorie
> 
> ![image](https://user-images.githubusercontent.com/76179120/109964055-d65a3580-7cf5-11eb-8379-fd3adf2bdb46.png)
> 
> 
> 
> Am largit putin bucata din dreapta ca sa-l si ghideze
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/76179120/109964170-fab61200-7cf5-11eb-81e0-af69d118d30c.png)
> 
> 
> 
>

**Comment by matei8** [comment]
Incerc sa printez eu pana luni

**Comment by matei8** [comment]
@LucaVictor esti sigur ca inelul nu intra sub piesa, adica nu e prea mare spatiul dintre tuburi si piesa ?

**Comment by TakingTheRisk** [comment]
> Nu cred că Alex are atâta spatiu

220x220x250, am destul

**Comment by LucaVictor** [comment]
> @LucaVictor esti sigur ca inelul nu intra sub piesa, adica nu e prea mare spatiul dintre tuburi si piesa ?

Nu, piesa pleaca de la nivelul extrusion-uluiz deci nu ar trb să fie o problema, o sa dau o poza mai încolo sa vezi

**Comment by matei8** [comment]
E ok ca m-am uitat si in fusion dar nu eram sigur daca erau masuratorile bune si d-aia te-am intrebat
