### ISSUE TITLE
Wabble Goal

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#21]

**Comment by matei8** [comment]
are cineva idei pt wabble ?

**Comment by LucaVictor** [comment]
O sa las aici poza discutata la sedinta de ieri

**Comment by LucaVictor** [comment]
![poza robot](https://user-images.githubusercontent.com/76179120/109629709-c94e1280-7b4c-11eb-929d-d7029e969339.jpg)

**Comment by matei8** [comment]
1 si 6 ar fi cele mai bune puncte

**Comment by MihaiBobeica** [comment]
Patratelele vor fi pe partea dreapta a terenului, deci am alege P6 pentru mecanism.

**Comment by MihaiBobeica** [comment]
![image](https://user-images.githubusercontent.com/77356043/109694571-a135d200-7b93-11eb-9521-76a10f787123.png)
 ma gandesc ca ceva de genul sa facem, in punctul negru sa fie un ax, iar pe semicercul rosu avem un gear ce se misca, astfel pune popica in pozitie verticala, o ridica, iar apoi o coboara in patrat

**Comment by matei8** [comment]
> Patratelele vor fi pe partea dreapta a terenului, deci am alege P6 pentru mecanism.

perfect

**Comment by matei8** [comment]
> ![image](https://user-images.githubusercontent.com/77356043/109694571-a135d200-7b93-11eb-9521-76a10f787123.png)
> ma gandesc ca ceva de genul sa facem, in punctul negru sa fie un ax, iar pe semicercul rosu avem un gear ce se misca, astfel pune popica in pozitie verticala, o ridica, iar apoi o coboara in patrat

True si atunci mai folosim un motor pt tot bratul ca sa-l ridicam ?

**Comment by MihaiBobeica** [comment]
> > ![image](https://user-images.githubusercontent.com/77356043/109694571-a135d200-7b93-11eb-9521-76a10f787123.png)
> > ma gandesc ca ceva de genul sa facem, in punctul negru sa fie un ax, iar pe semicercul rosu avem un gear ce se misca, astfel pune popica in pozitie verticala, o ridica, iar apoi o coboara in patrat
> 
> True si atunci mai folosim un motor pt tot bratul ca sa-l ridicam ?
> 

mă gândesc să folosim un motor ca să întoarcă acea roata π radiane. Nu înțeleg ideea de braț, cred că mai bine folosim o simplă roată ce se rotește atașată de robot daca înălțimea in '6' este cam cat înălțimea unui wobble

**Comment by matei8** [comment]
Pai da ala e bratul, si in capat are o "gheara" care apuca wabbleul  si cand roata aia de care zici tu se roteste, bratul se ridica si wabbleul cu el

**Comment by LucaVictor** [comment]
Putem  sa punem un core hex care roteste bratul pe axele Z,X(sus-jos), dupa care sa avem un servo  care activeaza ca o gheara  dupa cum a zis rancezu

**Comment by LucaVictor** [comment]
Cred ca pe 6 mergem cel mai bine

**Comment by MihaiBobeica** [comment]
Daca există o gheară nu avem nevoie de un motor in plus?

**Comment by LucaVictor** [comment]
ba da, asta ziceam dar iti dau o poza
![image](https://user-images.githubusercontent.com/76179120/109791855-958dee00-7c1b-11eb-89a5-214a98215dda.png)

In  chenarul verde se observa, core hex ul si servo ul.
link video: https://www.youtube.com/watch?v=-ujskulDkoo 0:29

**Comment by LucaVictor** [comment]
Core hex ul misca bratul sus jos, iar servo ul directioneaza gheara ca apuca

**Comment by amareto1234** [comment]
multa bafta baieti !
