### ISSUE TITLE
Amortizor Intake

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#24]
Amoritizorul de intake este folosit pentru a pune presiune aditionala pe rotile de 30mm din fata.

**Comment by Andrei-Iatagan** [comment]
propun arc lamelar, sustinut de o bara perpendiuclara pe podea, care sa fie pus pe bratul care tine rotitele de intake

**Comment by Andrei-Iatagan** [comment]
în afară de arc lamelar, care am constatat că este o soluție complicată, dacă și numai dacă este nevoie de apăsare în plus pe inel la intake, putem să folosim elastice (chiar și elastice de birou), astfel : din șasiu scoatem un șurub, scoatem un șurub și din brațul de la intake, punem piulițe în capătul șuruburilor și efectiv întindem câteva elastice care să apropie cele două șuruburi
poză reprezentativă atașată
![image](https://user-images.githubusercontent.com/77207103/105230233-b7e91200-5b6d-11eb-8b46-5866b5d760aa.png)
