### ISSUE TITLE
Intake --> Conveyer

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#25]
Trecerea din intake in conveyer(rampa+unghi+alte chestii ce mai e necesar)
Rezultatul final sa-l scrieti in Conveyer #18 
Maine seara la ora 22 termen limita

**Comment by Andrei-Iatagan** [comment]
https://www.youtube.com/watch?v=QHFo29VeIDY
(e prima echipa cu tambur pe care am vazut -o pana acum), si au un intake-: conveyer foarte simplu, cred ca e de urmarit

**Comment by Andrei-Iatagan** [comment]
IMO, ăsta e cel mai bun sistem de departe (cred că am mai zis de vreo 5 ori, dar mai zic)
https://www.youtube.com/watch?v=F8CD3CI4OKc&t=99s
totul este foarte simplu, tragerea se face foarte simplu, nu e nevoie de eu știu ce braț care să împingă în flywheel, sau de o cutie de carton care să țină inelele. De asemenea, trecerea de la intake la shooting e foarte simplă, nu strică inele (adică nu există șansa să - l prindă la colț să - l îndoaie)

**Comment by Andrei-Iatagan** [comment]
tl, dr : așa
![image](https://user-images.githubusercontent.com/77207103/105691397-dbadae80-5f05-11eb-9f84-c5e62a3beb7d.png)

**Comment by Andrei-Iatagan** [comment]
încă o chestie pe care am observat - o : foarte muște echipe încep cu brațul de intake ridicat. S - a uitat cineva de la noi până acum pe cât de mare trebuie să fie robotul ? (parcă în anii trecuți erau niște limite, și lumea începea cu roboții pliați)

**Comment by AndreiIatagan** [comment]
Sunt tot eu

**Comment by costaalacuparmare** [comment]
Rampa va fi formata din banda cauciucata (vezi prastii piata) care sa traga inele, tuburi chirurgicale sau policarbonat

**Comment by AndreiIatagan** [comment]
Având în vedere cele discutate astăzi în ședința referitoare la

**Comment by AndreiIatagan** [comment]
În cazul în care vom avea nevoie de un „foraș” efectiv, am decis să folosim o placă din material plastic rigid, de exemplu policarbonat
