### ISSUE TITLE
Shooter mobil

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#30]
Idei pt shooter sa tragem de oriunde

**Comment by matei8** [comment]
https://www.joom.com/en/products/5cc6ee071436d4010143a679
Daca am pune motorul pe drivetrain(sub shooter anyway) si dupa am pune axul de la flywheel in asta am salva spatiu (sa nu iesim din parametrii)

**Comment by TakingTheRisk** [comment]
Ca sa facem ceva de genul ar trebui sa regandim tot robotul tho? 
Ma rog, de la conveyor in sus
