### ISSUE TITLE
Cleste clasic

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#31]
O sa fie deschis pana sambata la ora 12:00 (am). Varianta clasica cu 2 motoare cu un cleste si un brat mobil.

**Comment by costaalacuparmare** [comment]
@LucaVictor cand ai timp sa vorbim ca sa faci un model CAD?

**Comment by LucaVictor** [comment]
Nu acm, dar după 8

**Comment by matei8** [comment]
Ma gandesc sa mai punem un C Channel pe C Channel-ul din exterior de la drivetrain, pe care sa montam un core hex, dar nu-mi prea dau seama cum putem sa fixam bratul pe care se afla clestele
