### ISSUE TITLE
Stivuitor

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#32]
O sa fie deschis pana sambata la ora 12:00 (am). Ridicarea wabbelui de sub el.

**Comment by MihaiBobeica** [comment]
In legatura cu Stivuitorul, voi pune mai multe imagini sa descriu ce am in minte

**Comment by MihaiBobeica** [comment]
![image](https://user-images.githubusercontent.com/77356043/110946166-392b7c80-8347-11eb-9e76-5f4cc2b7cb2b.png)
Dreptunghiul negru este robotul si partea albastra este elementul de wobble, probabil pus in spatele robotului

**Comment by MihaiBobeica** [comment]
![image](https://user-images.githubusercontent.com/77356043/110946395-7abc2780-8347-11eb-9241-5811ae574dcc.png)
 Ma gandesc la un fel de lift, care sa deplaseze zona Galbena in Zona verde, probabil prin niste curele/gears. Ma voi gandi in detaliu despre cum se ridica

**Comment by MihaiBobeica** [comment]
![image](https://user-images.githubusercontent.com/77356043/110946827-0cc43000-8348-11eb-8009-5c167a93c8cd.png)
Ma gandesc sa atasasm o suprafata pe zona verde din ceva asemanator gear-ului, ca un o roata gear sa se roteasca sa duca in sus, Daca nu e suficient o roata, putem adauga mai multe, nu ar fi asta o problema. Ma gandesc la acest design de ceva ce iese in exterior pentru a evita depasirea inaltimii maxime


De asemenea ma gandesc ca zona pe care stationeaza Wobble se poate misca analog zonei verzi

**Comment by MihaiBobeica** [comment]
![image](https://user-images.githubusercontent.com/77356043/110947219-8a883b80-8348-11eb-899a-f36d9f51c822.png)
 Stiu ca va plac desenele ( si ca sunt dificile de inteles), dar ma gandesc ca pentru a duce peste perete, stivuitorul sa fie plasat mai sus . Ma gandesc ca avanatajul la stivuitor este ca poate fi compactizat, urmand in timpul meciului sa se extinda la nevoie. Avantajul 2 ma gandesc ca este rapid si precis, bazandu-se in mare parte pe eficienta DriveTrainului

**Comment by matei8** [comment]
Inca o chestie, ca sa mearga ideea cu stivuitorul, wabbleul trebuie sa ajunga deasupra robotului(ca sa fie mai inalt decat gardul adk 34 cm sau cv de genu)
Asadar, ma gandesc ca ne trebuie un sistem care sa functioneze intr-o raza de 35 cm

**Comment by matei8** [comment]
> ![image](https://user-images.githubusercontent.com/77356043/110947219-8a883b80-8348-11eb-899a-f36d9f51c822.png)
> Stiu ca va plac desenele ( si ca sunt dificile de inteles), dar ma gandesc ca pentru a duce peste perete, stivuitorul sa fie plasat mai sus . Ma gandesc ca avanatajul la stivuitor este ca poate fi compactizat, urmand in timpul meciului sa se extinda la nevoie. Avantajul 2 ma gandesc ca este rapid si precis, bazandu-se in mare parte pe eficienta DriveTrainului

nu cred ca poate sa fi foarte rapid pt ca trebuie sa tina wabbleul stabil

**Comment by MihaiBobeica** [comment]
Un stivuitor industrial are barile puse paralel, mă gândesc că putem găsi un unghi astfel încât să stea mai fix acolo
