### ISSUE TITLE
Roti intake

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#35]
Spatiu dintre rotitele de la intake e ineficient si inelul se blocheaza acolo

**Comment by Andrei-Iatagan** [comment]
Dupa parerea mea, daca am putea sa facem rost de tub chirurgical, aceasta problema ar putea fi rezolvata foarte simplu : practic, rotile de la intake vor deveni un conveyer mai mic. le inlocuim cu niste scripeti (care sunt destul de sigur ca pot fi printati 3D, pentru ca nu e nevoie de tensiune prea mare in tub).
    O alta varianta cred ca ar putea fi tentacule (sau ca am vazut de curand la neurobotix, pamatuf),care sa inlocuiasca efectiv rotitele. Practic ar avea efectul unor roti mai mari, dar nu sunt afectate asa de rau de distanta mica pana la pamant. dar nu sunt foarte sigur daca ar merge (trebuie sa ma gandesc putin mai bine)
    Inca o varianta posibila, care nu are nevie de piese suplimentare (poate de cateva rotite ca alea deja puse acolo), ar fi sa formam un fel de scripeti (ca la primul alineat), dar in loc de tuburi chirurgicale sa folosim elastice de birou (sunt constient de faptul ca le vom schimba destul de des, dar cred ca pentru 3 - 4 meciuri tin, si cand se rupe unul nu e mare paguba, daca sunt destule). [practic, unim rotitele 2 cate 2, nu e neaparat sa le lipim, poate fi facut si cu spacere, si intre cele 2 roti dintr - o pereche, sta cate un elastic, care, pentru o mai usoara instalare, va fi rupt, dupa legat (sa nu scoatem rotitele axle - urile cu roti). Care este avantajul peste chestia cu soricei de dinainte ? viteza elasticului va fi egala cu cea a rotii, si elasticul se va invarti, tragand si el de inel (nu va sta pe loc, doar sa nu cada inelul, cum era cazul la soricei)]

**Comment by Andrei-Iatagan** [comment]
Si rog insistent pe Matei sa nu ma injure pentru issue - uri.

**Comment by matei8** [comment]
Sunt de acord cu idee de mini conveyer plus ca asa o sa avem loc finally de 3 inele insa zic sa lasam rotitele alea de 30 mm pt ca propulseaza bine inelul

**Comment by matei8** [comment]
Cred ca problema este defapt spatiul dintre cele doua axuri cu rotite unde propun sa punem niste curele mici care se prind pe niste rotite zimtate f mici pe care le avem in kit si sunt facute pt asta

**Comment by Andrei-Iatagan** [comment]
<p>
legat de ce e mai sus : daca folosim rotite foarte mici si nu rotite cu acelasi diametru cu cele deja puse (sau poate le folosim direct pe cele de acolo), viteza miniconveyerului va fi mai mica decat viteza rotilor => inelul va fi incetinit. In cazul in care nimic nu merge, putem sa folosim roti mai mici.     
</p>

**Comment by Andrei-Iatagan** [comment]
<p>
legat de curele, m - am uitat si eu pe optimus digital si pe ardushop. Toate curelele pe care le - am vazut eu pe acolo erau pentru imprimatre 3d, toate cam cu aceleasi dimensiuni, late de 10 / 6mm. Am mai gasit si asta, care pare folosibila, fiind atat de scurta (e inchisa) 
</p>

**Comment by Andrei-Iatagan** [comment]
![image](https://user-images.githubusercontent.com/77207103/112267488-34879200-8c7e-11eb-84b3-6a90f4c8b40d.png)

**Comment by matei8** [comment]
> legat de curele, m - am uitat si eu pe optimus digital si pe ardushop. Toate curelele pe care le - am vazut eu pe acolo erau pentru imprimatre 3d, toate cam cu aceleasi dimensiuni, late de 10 / 6mm. Am mai gasit si asta, care pare folosibila, fiind atat de scurta (e inchisa)

da da da sunt bune pt ca am eu aici langa mine la imprimanta si au aderenta buna

**Comment by matei8** [comment]
> legat de ce e mai sus : daca folosim rotite foarte mici si nu rotite cu acelasi diametru cu cele deja puse (sau poate le folosim direct pe cele de acolo), viteza miniconveyerului va fi mai mica decat viteza rotilor => inelul va fi incetinit. In cazul in care nimic nu merge, putem sa folosim roti mai mici.

Well u got a point dar, tot vor fi impinse spre conveyer si important e sa mai poata sa tina inca un inel

**Comment by Andrei-Iatagan** [comment]
Nu este cea mai stralucita idee, pentru ca servo - urile sunt destul de sensibile, dar daca poate cineva imbunatati, astept raspunsuri
![image](https://user-images.githubusercontent.com/77207103/112369584-01c4b480-8ce5-11eb-9670-a89a337c2c9c.png)

**Comment by Andrei-Iatagan** [comment]
Acum intake - ul are doua probleme : sa nu ajunga prea jos (sa nu ajunga pe pamant), sa nu ajunga prea sus(adica sa nu poata intra mai mult de un inel odata pe sub el)

**Comment by Andrei-Iatagan** [comment]
O posibila solutie pentru prima problema (sa nu ajunga intake - ul prea jos) este sa folosim doua sfori / suspante de lungime egala, care sa nu permita intake - ului sa ajunga pe sol. (atasez o poza, vor fi asemanatoare cu portile de castel ... :)  )
![image](https://user-images.githubusercontent.com/77207103/112380863-908bfe00-8cf2-11eb-96bf-6252652c7091.png)

**Comment by Andrei-Iatagan** [comment]
Intake - ul joaca foarte mult. Aceasta problema poate fi rezolvata fie prin limita superioara, fie prin cresterea masei intake - ului. O metoda pentru a pune greutate pe intake, ar fi sa printam 3D 2 piese in forma de U, care sa tina o teava / bara / Channel cu greutate variabila.
 Atasez o poza care sa descrie mai bine ce am zis

**Comment by Andrei-Iatagan** [comment]
![image](https://user-images.githubusercontent.com/77207103/112381901-d1d0dd80-8cf3-11eb-8c27-85d8197ddaad.png)

**Comment by Andrei-Iatagan** [comment]
![image](https://user-images.githubusercontent.com/77207103/112382595-b7e3ca80-8cf4-11eb-8f08-c99a13bd6a1f.png)

**Comment by Andrei-Iatagan** [comment]
<p>Cred ca am mai gasit o mica optimizare pentru intake : punem soricei pe roti.</p>
<p>Atasez poza</p>
<p>Nu e ceva wow, dar cred că poate să facă intake - ul să meargă *puțin* mai bine</p>
![image](https://user-images.githubusercontent.com/77207103/112955882-8b8eda80-9148-11eb-9dfe-1a434bca5cc2.png)

**Comment by Andrei-Iatagan** [comment]
![image](https://user-images.githubusercontent.com/77207103/112955910-90ec2500-9148-11eb-8aff-e822bf0089dd.png)

**Comment by Andrei-Iatagan** [comment]
valabil <=> un soricel are loc sa treaca de extrusion - ul pus intre cele 2 brate de la intake. Nu cred ca ar fi o mare imbunatatire.
