### ISSUE TITLE
Probleme Drivetrain

### ISSUE THREAD

**Issue by matei8** [Sova-Tech/FTC#44]
Se misca greu partea stanga si intra des inele sub el

**Comment by Andrei-Iatagan** [comment]
<p>trebuie dezmembrat, reasamblaat, pentru a ne asigura ca nicio piesa nu este prost montata.</p>
<p>ungem lanturi / angrenaje</p>
<p>punem un fel de "body kit", practic, ce am pus si langa intake, care sa nu permita inelelor sa intre sub el</p>
<p>facem *cumva* sa nu mai faca wheelie ... ?</p>

**Comment by Andrei-Iatagan** [comment]
<p>un fel de aparatoare la roti ne - ar putea scuti si de o alta problema. Uneori, un inel e blocat la o roata, si e nevoie de multe miscari sa il scoatem de acolo</p>

**Comment by matei8** [comment]
@Mihai-Solescu incearca sa gasesti o metoda ca atunci cand pornim in fata si in spate sa accelereze mai usor, dar nu si cand se roteste pt ca ne trebuie viteza aia de rotatie pe loc.
